### ISSUE TITLE
Please add a separate license file

### ISSUE THREAD

**Issue by QuLogic** [yihui/mime#7]
It is useful to have a separate LICENSE file that contains the text of the license (GPLv2 in this case). This is a) one of the [recommended steps](https://www.gnu.org/licenses/gpl-howto.html) by the FSF, b) useful for packagers (outside of CRAN, obviously) and c) [parseable by GitHub](https://github.com/blog/2252-license-now-displayed-on-repository-overview) to appear in its metadata/search.

**Comment by yihui** [comment]
I understand all these advantages, but I'm at the mercy of CRAN maintainers as a package developer, and I have to follow the strange rule that I cannot include a verbatim copy of the GPL license in the source package but simply indicate the license in DESCRIPTION, otherwise `R CMD check` will show a NOTE:

```
* checking DESCRIPTION meta-information ... NOTE
License components with restrictions not permitted:
  GPL + file LICENSE
```

Please feel free to make suggestions to CRAN to allow package authors include an actual LICENSE file in packages.

BTW, @jimhester has been working on c) (parsing an R package's DESCRIPTION). I'm not sure about the progress.
